=== janmartendeboer/feed/schemas/feed.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://raw.githubusercontent.com/johmanx10/feed/main/schemas/feeds.json",
  "type": "object",
  "properties": {
    "enabled": {
      "title": "Enabled",
      "$comment": "Whether the feed will be processed.",
      "type": "boolean"
    },
    "name": {
      "title": "Name",
      "$comment": "The unique name for the feed.",
      "type": "string",
      "minLength": 1,
      "maxLength": 80
    },
    "url": {
      "title": "URL",
      "$comment": "The URL that points to the feed.",
      "type": "string",
      "minLength": 1
    },
    "documentPath": {
      "title": "Document path",
      "$comment": "JMESPath selector for individual feed items.",
      "type": "string",
      "minLength": 1
    },
    "filters": {
      "title": "Filters",
      "$comment": "Filter out unwanted items.",
      "type": "array",
      "minItems": 1,
      "items": {
        "title": "Constraint",
        "$comment": "JMESPath filter constraint.",
        "type": "string",
        "minLength": 1
      }
    },
    "projection": {
      "title": "Projection",
      "$comment": "Determine the structure of the output.",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": {
        "title": "Expression",
        "$comment": "JMESPath expresison.",
        "type": "string",
        "minLength": 1
      }
    }
  },
  "required": ["enabled", "name", "url", "documentPath"]
}

=== janmartendeboer/feed/feeds/tweakers.json
{
  "$schema": "../schemas/feed.json",
  "enabled": true,
  "name": "Tweakers.net Nieuws",
  "url": "http://feeds.feedburner.com/tweakers/mixed",
  "documentPath": "channel.item[*]",
  "projection": {
    "title": "title",
    "url": "guid",
    "date": "pubDate",
    "description": "description",
    "image": "'https://tweakers.net/logo.png'"
  },
  "filters": [
    "contains(category, 'Nieuws') || category == 'Nieuws'"
  ]
}

=== janmartendeboer/feed/feeds/nu-nl.json
{
  "$schema": "../schemas/feed.json",
  "enabled": false,
  "name": "Nu.nl",
  "url": "https://www.nu.nl/rss",
  "documentPath": "channel.item[*]",
  "filters": [
    "!contains(category, 'Sport') && category != 'Sport'"
  ],
  "projection": {
    "title": "title",
    "url": "guid",
    "date": "pubDate",
    "description": "description",
    "image": "enclosure.\"@attributes\".url"
  }
}
